Repository team-morado/tech-info-sharing-note, pull requests merged in 2022-03, with the labels that each got.

#36 Header 컴포넌트 내 버튼 표시 기능 생성
  public/images/logo.svg
  src/components/Footer.js
  src/components/Header.js
  src/components/Svg.js
  src/elements/NextBtn.js
  src/pages/NotFound.js
Labels: :question: question, :sparkles: Feature, :nail_care: Style

#48 Header location 코드 수정
  src/components/Header.js
  src/elements/NextBtn.js
  src/pages/Home.js
Labels: :bug: bug

#49 뷰페이지 작성시간 표시
  src/pages/ViewPage.js
Labels: :hammer_and_wrench: Refactor

#53 Loading 컴포넌트 추가
  package.json
  src/components/Header.js
  src/components/Spinner.js
  src/elements/Button.js
  src/pages/Loading.js
  src/pages/NotFound.js
  yarn.lock
Labels: :nail_care: Style, :hammer_and_wrench: Refactor

#58 서버 데이터를 연동한 카테고리 및 수정하기 기능
  src/App.js
  src/pages/Edit.js
  src/pages/Home.js
  src/pages/ViewPage.js
  src/shared/redux/modules/techInfo.js
Labels: :sparkles: Feature, :hammer_and_wrench: Refactor

#67 :recycle: Loading 기능 구현
  src/App.js
  src/pages/Home.js
  src/pages/Loading.js
  src/shared/redux/modules/techInfo.js
Labels: :sparkles: Feature, :hammer_and_wrench: Refactor

#69 Splash, NotFound, Loading 배치 변경 및 스타일 수정
  src/components/Header.js
  src/components/Spinner.js
  src/pages/Home.js
  src/pages/Loading.js
  src/pages/NotFound.js
  src/pages/Splash.js
Labels: :nail_care: Style

#70 Splash 페이지 넘기는 이슈 해결
  src/App.js
  src/components/Header.js
  src/elements/NextBtn.js
  src/pages/Home.js
  src/pages/NotFound.js
  src/pages/Splash.js
Labels: :sparkles: Feature, :hammer_and_wrench: Refactor

#72 tagColor 컬러 변경
  src/elements/CategoryTag.js
Labels: :nail_care: Style

#73 etc 카테고리 추가
  src/App.js
  src/Util/Common.js
  src/components/Common.js
  src/components/ListOptionGroup.js
  src/components/index.js
  src/pages/Edit.js
  src/pages/Home.js
  src/pages/New.js
  src/pages/index.js
Labels: :sparkles: Feature, :hammer_and_wrench: Refactor

#76 📝 Readme 1차 작성 완료
  README.md
Labels: :memo: Docs

#77 📝 Readme 작업상세내용, 시안 부분 수정
  README.md
Labels: :memo: Docs
