Repository team-morado/tech-info-sharing-note, pull requests merged in 2022-02, with the labels that each got.

#2 test
  test.html
Labels: help wanted

#13 뷰페이지 스타일 작업
  src/App.js
  src/components/Svg.js
  src/components/ViewCard.js
  src/pages/Home.js
  src/pages/ViewPage.js
Labels: :question: question, :nail_care: Style

#15 Splash, Header, Footer, NotFound 컴포넌트 추가
  public/favicon.ico
  public/index.html
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/image/icon-arrow-left.svg
  src/image/icon-edit.png
  src/image/logo.svg
  src/pages/Home.js
  src/pages/New.js
  src/pages/NotFound.js
  src/pages/Splash.js
Labels: :nail_care: Style

#16 ♻️ 코드 리팩토링
  src/App.js
  src/components/Header.js
  src/components/ListItem.js
  src/components/index.js
  src/elements/index.js
  src/pages/Home.js
  src/pages/New.js
  src/pages/ViewPage.js
  src/pages/index.js
Labels: :hammer_and_wrench: Refactor

#21 뷰페이지 기능 구현
  src/components/ClipboardCopy.js
  src/components/Svg.js
  src/components/ViewCard.js
  src/pages/ViewPage.js
Labels: :question: question, :sparkles: Feature

#23 redux 설치 및 스타일 코드 수정
  package.json
  src/elements/Button.js
  src/image/icon-arrow-down.svg
  src/pages/New.js
  yarn.lock
Labels: :nail_care: Style

#28 💄 ListItem UI 구현 2차
  src/App.js
  src/components/ListItem.js
Labels: :nail_care: Style

#32 import 방식 변경
  src/components/index.js
Labels: :hammer_and_wrench: Refactor

#34 ContentInner 추가 관련 스타일 변경 및 스크립트 작업
  src/App.css
  src/App.js
  src/components/Common.js
  src/components/Footer.js
  src/components/Header.js
  src/components/ListOption.js
  src/components/ListOptionGroup.js
Labels: :sparkles: Feature, :nail_care: Style
